set(repository_headers
        ${header_path}/lzhlib/repository/dynamic_repository.hpp
        ${header_path}/lzhlib/repository/indexed_repository.hpp
        ${header_path}/lzhlib/repository/light_weight_repository.hpp
        ${header_path}/lzhlib/repository/repository.hpp
        ${header_path}/lzhlib/repository/sparse_indexed_repository.hpp
        ${header_path}/lzhlib/repository/stable_repository.hpp
        ${header_path}/lzhlib/repository/stock_id.hpp
        )